vich_uploader:
    db_driver: orm

    mappings:
        videos:
            uri_prefix:         '%app.path.videos%'
            upload_destination: '%kernel.project_dir%/public%app.path.videos%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
